server:
  port: 80
feign: 
  hystrix: 
    enabled: true 
  
  compression:
    request:
      enabled: true
      mime-types:
      - text/xml
      - application/xml
      - application/json
      min-request-size: 2048

logging:
  level:
    cn.mldn.microcloud.service: DEBUG
    
eureka: 
  client:
    register-with-eureka: false # 不在eureka中进行注册
    service-url:
      defaultZone: http://edmin:hello@eureka-7001.com:7001/eureka,http://edmin:hello@eureka-7002.com:7002/eureka,http://edmin:hello@eureka-7003.com:7003/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true   # 底部显示IP地址