feign:
  compression:
    response: 
      enabled: true
      
eureka: 
  client:
    service-url:
      defaultZone: http://edmin:hello@eureka-7001.com:7001/eureka,http://edmin:hello@eureka-7002.com:7002/eureka,http://edmin:hello@eureka-7003.com:7003/eureka
  instance:
    instance-id: dept-8003.com
    prefer-ip-address: true   # 底部显示IP地址
    
info:
  app.name: mldn-microcloud-dept
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # 定义mybatis核心配置文件的路径
  type-aliases-package: cn.mldn.microcloud.vo       # 定义别名出现的开发包
  mapper-locations:
  - classpath:mybatis/mapping/**/*.xml            # 所有的映射文件路径

spring: 
  application:
    name: microcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 配置数据源类型
    url: jdbc:mysql://localhost:3306/dept8003     # 数据库的连接地址
    driver-class-name: org.gjt.mm.mysql.Driver    # 驱动程序
    username: root                                # 用户名
    password: mysqladmin                          # 密码
    dbcp2:                                        # 数据库连接池配置
      min-idle: 1                                 # 最小维持连接数
      max-idle: 1                                 # 最大维持连接数
      max-total: 1                                # 最大的可用连接数
      max-wait-millis: 200                        # 最大等待时间
      initial-size: 1                             # 初始化连接数
server: 
  port: 8003                                      # 定义服务端口

